export const scpData = {
    '001': '[AWAITING DE-CLASSIFICATION]',
    '002': 'The "Living" Room',
    '003': 'Biological Motherboard',
    '004': 'The 12 Rusty Keys and the Door',
    '005': 'Skeleton Key',
    '006': 'Fountain of Youth',
    '007': 'Abdominal Planet',
    '008': 'Zombie Plague',
    '009': 'Red Ice',
    '010': 'Collars of Control',
    '011': 'Sentient Civil War Memorial Statue',
    '012': 'A Bad Composition',
    '013': 'Blue Lady Cigarettes',
    '014': 'The Concrete Man',
    '015': 'Pipe Nightmare',
    '016': 'Sentient Micro-Organism',
    '017': 'Shadow Person',
    '018': 'Super Ball',
    '019': 'The Monster Pot',
    '020': 'Unseen Mold',
    '021': 'Skin Wyrm',
    '022': 'The Morgue',
    '023': 'Black Shuck',
    '024': 'Game Show of Death',
    '025': 'A Well-Worn Wardrobe',
    '026': 'Afterschool Retention',
    '027': 'The Vermin God',
    '028': 'Knowledge',
    '029': 'Daughter of Shadows',
    '030': 'The Homunculus',
    '031': 'What is Love?',
    '032': 'Brother\'s Bride',
    '033': 'The Missing Number',
    '034': 'Obsidian Ritual Knife',
    '035': 'Possessive Mask',
    '036': 'The Reincarnation Pilgrimage of the Yazidi (Kiras Guhorîn)',
    '037': 'Dwarf Star',
    '038': 'The Everything Tree',
    '039': 'Proboscis Engineers',
    '040': 'Evolution\'s Child',
    '041': 'Thought-Broadcasting Patient',
    '042': 'A Formerly Winged Horse',
    '043': 'The Beatle',
    '044': 'World War II Era Molecular-Fission Cannon',
    '045': 'Atmospheric Converter',
    '046': '"Predatory" Holly Bush',
    '047': 'Microbial Mutagen',
    '048': 'The Cursed SCP Number',
    '049': 'Plague Doctor',
    '050': 'To The Cleverest',
    '051': 'Japanese Obstetrical Model',
    '052': 'Time-Traveling Train',
    '053': 'Young Girl',
    '054': 'Water Nymph',
    '055': '[unknown]',
    '056': 'A Beautiful Person',
    '057': 'The Daily Grind',
    '058': 'Heart of Darkness',
    '059': 'Radioactive Mineral',
    '060': 'Infernal Occult Skeleton',
    '061': 'Auditory Mind Control',
    '062': '"Quantum" Computer',
    '063': '"The World\'s Best TothBrush"',
    '064': 'Flawed von Neumann Structure',
    '065': 'Destroyed Organic Catalyst',
    '066': 'Eric\'s Toy',
    '067': 'The Artist\'s Pen',
    '068': 'The Wire Figure',
    '069': 'Second Chance',
    '070': 'Iron Wings',
    '071': 'Degenerative Metamorphic Entity',
    '072': 'The Foot of the Bed',
    '073': '"Cain"',
    '074': 'Quantum Woodlouse',
    '075': 'Corrosive Snail',
    '076': '"Able"',
    '077': 'Rot Skull',
    '078': 'Guilt',
    '079': 'Old AI',
    '080': 'Dark Form',
    '081': 'Spontaneous Combustion Virus',
    '082': '"Fernand" the Cannibal',
    '083': 'An Abandoned Row Home',
    '084': 'Static Tower',
    '085': 'Hand-drawn \'\'Cassy\'\'',
    '086': 'The Office of Dr. [REDACTED]',
    '087': 'The Stairwell',
    '088': 'The Lizard King',
    '089': 'Tophet',
    '090': 'Apocorubik\'s Cube',
    '091': 'Nostalgia',
    '092': '"The Best of The 5th Dimension"',
    '093': 'Red Sea Object',
    '094': 'Miniature Event Horizon',
    '095': 'The Atomic Adventures of Ronnie Ray-Gun',
    '096': 'The "Shy Guy"',
    '097': 'Old Fairgrounds',
    '098': 'Surgeon Crabs',
    '099': 'The Portrait',
    '100': '"Jamaican Joe\'s Junkyard Jubilee"',
    '101': 'Hungry Bag',
    '102': 'Property of Marshall, Carter, and Dark Ltd.',
    '103': 'The Never-Hungry Man',
    '104': 'The Lonely Ball',
    '105': '"Iris"',
    '106': 'The Old Man',
    '107': 'The Turtle Shell',
    '108': 'Extradimensional Nasal Cavity',
    '109': 'Infinite Canteen',
    '110': 'Subterranean City',
    '111': 'Dragon-Snails™',
    '112': 'The Variable Coaster',
    '113': 'The Gender-Switcher',
    '114': 'Bringer of Conflict',
    '115': 'Miniature Dump Truck',
    '116': 'The Brittle Boy',
    '117': 'Complete Multitool',
    '118': 'Nuclear Protists',
    '119': 'Timecrowave',
    '120': 'Teleporting Paddling Pool',
    '121': 'Concrete Cradle',
    '122': 'No More Monsters',
    '123': 'Contained Miniature Black Hole',
    '124': 'Fertile Soil',
    '125': 'Contagious Reflection',
    '126': 'Invisible Friend',
    '127': 'The Living Gun',
    '128': 'Kinetic Energy Entity',
    '129': 'Progressive Fungal Infection',
    '130': 'Post Office',
    '131': 'The "Eye Pods"',
    '132': 'Broken Desert',
    '133': 'Instant Hole',
    '134': 'Star-Eyed Child',
    '135': 'Universal Carcinogen',
    '136': 'Naked Doll',
    '137': 'The Real Toy',
    '138': 'The Ever-Living Man',
    '139': 'Possible Skull of the White Div',
    '140': 'An Incomplete Chronicle',
    '141': 'Codex Damnatio',
    '142': 'One-Armed Bandit',
    '143': 'The Bladewood Grove',
    '144': 'Tibetan Rope to Heaven',
    '145': 'Man-Absorbing Phone',
    '146': 'Bronze Head of Shame',
    '147': 'Anachronistic Television',
    '148': 'The "Telekill" Alloy',
    '149': 'The Blood Flies',
    '150': 'Ship of Theseus',
    '151': 'The Painting',
    '152': 'Book of Endings',
    '153': 'Drain Worms',
    '154': 'Offensive Bracelets',
    '155': 'Infinite Speed Computer',
    '156': 'Reanimating Pomegranate',
    '157': 'Mimetic Predator',
    '158': 'Soul Extractor',
    '159': 'The Perfect Lock',
    '160': 'Predator Drone',
    '161': 'Pinwheel of Doom!',
    '162': 'Ball of Sharp',
    '163': 'An Old Castaway',
    '164': 'Squid Tumors',
    '165': 'The Creeping, Hungry Sands of Tule',
    '166': 'Teenage Succubus',
    '167': 'Infinite Labyrinth',
    '168': 'Sentient Calculator',
    '169': 'The Leviathan',
    '170': 'A Tube of Superglue',
    '171': 'Collective Brain Foam',
    '172': 'The Gearman',
    '173': 'The Sculpture',
    '174': 'Ventriloquist\'s Dummy',
    '175': 'Treasure Map',
    '176': 'Observable Time Loop',
    '177': 'Checkmate',
    '178': '"3-D" Specs',
    '179': 'Sauelsuesor',
    '180': 'Identity Thieving Hat',
    '181': '"Lucky"',
    '182': '"Rider"',
    '183': '"Weaver"',
    '184': 'The Architect',
    '185': 'The Radio',
    '186': 'To End All Wars',
    '187': 'Double Vision',
    '188': 'The Craftsman',
    '189': 'Hair-Imitating Parasite',
    '190': 'A Prize Toybox',
    '191': 'Cyborg Child',
    '192': 'Flawless X-Ray Machine',
    '193': 'The Tissue Snail',
    '194': 'Carrion Host',
    '195': 'A "Medicinal Whiskey"',
    '196': 'Time Paradox',
    '197': 'The Greenhouse',
    '198': 'Cup of Joe',
    '199': 'Ferns',
    '200': 'Chrysalis'
};

export const maxSCPNUMBER = 200;